# Generated by Django 6.0.4 on 2026-05-21 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('sogliaPunti', models.IntegerField()),
                ('categoria', models.CharField(choices=[('tari', 'Sconto TARI'), ('servizio', 'Servizio Pubblico')], default='servizio', max_length=50)),
                ('attivo', models.BooleanField(default=True)),
                ('icona', models.CharField(default='🎁', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipologiaRifiuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unita_di_misura', models.CharField(max_length=10)),
                ('punti_per_unita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cittadino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_fiscale', models.CharField(max_length=16, unique=True)),
                ('indirizzo', models.CharField(max_length=255)),
                ('saldo_ecopunti', models.IntegerField(default=0)),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperatoreEcologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_fiscale', models.CharField(max_length=16, unique=True)),
                ('codice_identificativo', models.CharField(max_length=50, unique=True)),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RichiestaPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('in_attesa', 'In Attesa'), ('processato', 'Processato (Flusso Generato)')], default='in_attesa', max_length=20)),
                ('cittadino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_rifiuti.cittadino')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_rifiuti.premio')),
            ],
        ),
        migrations.CreateModel(
            name='Conferimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('quantita', models.DecimalField(decimal_places=2, max_digits=8)),
                ('punti_generati', models.IntegerField(blank=True, null=True)),
                ('cittadino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_rifiuti.cittadino')),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione_rifiuti.operatoreecologico')),
                ('rifiuto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestione_rifiuti.tipologiarifiuto')),
            ],
        ),
    ]
